---
- hosts: switches
  connection: local
  vars:
    cli:
      host: "{{ inventory_hostnae }}"
      username: "admin"
      password: "ssssss"

  tasks:
      - name: run show version
        ios_command:
          commands: "show version"
          provider: "{{ cli }}"
        register: show_version

      - name: debug me
        debug: var=show_version
